### ISSUE TITLE
Несовместимость с последней версией HD GUI 2

### ISSUE THREAD

**Issue by DelmorS** [TimTH98/SADX-Russian-Translation#1]
Привет!

Похоже, что перевод перестал работать с последней версией HD GUI 2.

Весь текст теперь выглядит как кракозябры, если запускать через sonicRUS.exe:
https://i.ibb.co/LCbj9JP/image.png

То же самое для диалогов, системных сообщений, итд.

Если запускать через sonic.exe то английский текст отображается нормально.
Если отключить HD GUI 2, и запускать через sonicRUS.exe, то все работает, русские буквы отображаются.

Использовал последнюю версию перевода 2.05 с Gamebanana:
https://gamebanana.com/mods/49995

**Comment by TimTH98** [comment]
В актуальной версии 2.1а ошибка исправлена х)
